# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Setup
version:            1
title:              SoDUCo
tagline:            ": <span style='color:#f9734a'>So</span>cial <span style='color:#f9734a'>D</span>ynamics in <span style='color:#f9734a'>U</span>rban <span style='color:#f9734a'>Co</span>ntext <br/> Open tools, models and data - Paris and its suburbs, 1789-1950"
description:         "ANR-18-CE38-0013, 2019-2023"
url:                 "https://soduco.github.io"
contact:             contact@geohistoricaldata.org
baseurl:             ''
permalink:           pretty
paginate: 1

github:
    repo:            https://github.com/soduco



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
