name: null
title: null
logo: /assets/img/logo.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

vendor: {
  show_organization: true
  organization_url: https://github.com/soduco
}
